services:
  postgres:
    image: postgres:latest
    container_name: finance-ai-database
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance-ai
    ports:
      - "5432:5432"
    volumes:
      - ./infra/.postgres-data:/var/lib/postgresql/data
